services:
  - type: web
    name: Music_service
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Music_service.wsgi --log-file -"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Music_service.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "1"
    staticPublishPath: staticfiles