# Generated by Django 5.0.4 on 2024-05-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
